name: peach
description: "A realtime chatting app focused on fast data transmission and updates with unique user interface while maintaining high functionality and performance for better user experience."

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-66.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  firebase_messaging: ^14.7.9
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0

  intl: ^0.19.0
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  visibility_detector: ^0.4.0+2
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1
  flutter_local_notifications: ^16.3.0
  flutter_cache_manager: ^3.3.1
  http: ^1.1.2
  image_picker: ^1.0.6
  shared_preferences: ^2.2.2
  audio_waveforms: ^1.0.4
  path_provider: ^2.1.2
  audioplayers: ^5.2.1
  google_mlkit_barcode_scanning: ^0.10.0
  camera: ^0.10.5+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true


  assets:
    - images/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Thin.ttf
          weight: 100
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter-Black.ttf
          weight: 900

#    - family: NotoColorEmoji
#      fonts:
#        - asset: fonts/NotoColorEmoji-Regular.ttf